import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import KakaoScript from '@/providers/KakaoScript'

const inter = Inter({ subsets: ['latin'] })

declare global {
    interface Window {
        Kakao: any
    }
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

//모바일 input 확대 방지
export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
            <KakaoScript />
        </html>
    )
}
